In [187]:
import pandas as pd
import numpy as np

In [188]:
df=pd.read_csv("jogadores.csv")

In [189]:
df.shape

(32, 1)

In [190]:
df[["Jogo 1","Jogo 2", "Jogo 3", "Jogo 4", "Pontos"]]=0

In [191]:
df1=df.sample(8)

In [192]:
df.drop(df1.index,inplace=True)

In [193]:
df2=df.sample(8)

In [194]:
df.drop(df2.index,inplace=True)

In [195]:
df3=df.sample(8)
df.drop(df3.index,inplace=True)

In [196]:
df4=df

In [197]:
df2

Nick  Jogo 1  Jogo 2  Jogo 3  Jogo 4  Pontos
31       random5       0       0       0       0       0
21       Pazzini       0       0       0       0       0
13  xiellendario       0       0       0       0       0
28       random2       0       0       0       0       0
3          Eddd        0       0       0       0       0
29       random3       0       0       0       0       0
5   KDA Guiczar        0       0       0       0       0
24         Bieul       0       0       0       0       0

In [198]:
df1.to_csv("j1_Rodada-1.csv")
df2.to_csv("j2_Rodada-1.csv")
df3.to_csv("j3_Rodada-1.csv")
df4.to_csv("j4_Rodada-1.csv")

In [199]:
df_t=pd.concat([df1,df2,df3,df4])

In [200]:
df_t

Nick  Jogo 1  Jogo 2  Jogo 3  Jogo 4  Pontos
9                DiPano        0       0       0       0       0
17                Kazumi       0       0       0       0       0
8              BES Toddy       0       0       0       0       0
11                Techzz       0       0       0       0       0
22        Gabriel Passos       0       0       0       0       0
6                  Godi        0       0       0       0       0
0              koke TFT        0       0       0       0       0
26                Eunuco       0       0       0       0       0
31               random5       0       0       0       0       0
21               Pazzini       0       0       0       0       0
13          xiellendario       0       0       0       0       0
28               random2       0       0       0       0       0
3                  Eddd        0       0       0       0       0
29               random3       0       0       0       0       0
5           KDA Guiczar        0       0       0       0       0
24                 Bieul       0       0       0       0       0
23           carluuuuuus       0       0       0       0       0
2   Guilherme Maximiano        0       0       0       0       0
12               Pedroca       0       0       0       0       0
16                 Dugra       0       0       0       0       0
25        Miguel Arkjow        0       0       0       0       0
1                F 0 J O       0       0       0       0       0
14                 Nyash       0       0       0       0       0
4                 Kyoto        0       0       0       0       0
7       Highroller Bnas        0       0       0       0       0
10           Leo peixoto       0       0       0       0       0
15               Missao        0       0       0       0       0
18                 Maahs       0       0       0       0       0
19                  Xaue       0       0       0       0       0
20                Sartii       0       0       0       0       0
27               random1       0       0       0       0       0
30              random4        0       0       0       0       0

In [201]:
df_t=df_t[["Nick","Pontos"]]

In [202]:
df_t.reset_index(inplace=True,drop=True)

In [203]:
df_t.index+=1

In [204]:
# df_t.Pontos = np.random.randint(4,40, size=len(df_t))

In [205]:
df_t=df_t.sort_values("Pontos",ascending=False)

In [206]:
df_t

Nick  Pontos
1                DiPano        0
2                 Kazumi       0
31               random1       0
30                Sartii       0
29                  Xaue       0
28                 Maahs       0
27               Missao        0
26           Leo peixoto       0
25      Highroller Bnas        0
24                Kyoto        0
23                 Nyash       0
22               F 0 J O       0
21        Miguel Arkjow        0
20                 Dugra       0
19               Pedroca       0
18  Guilherme Maximiano        0
17           carluuuuuus       0
16                 Bieul       0
15          KDA Guiczar        0
14               random3       0
13                 Eddd        0
12               random2       0
11          xiellendario       0
10               Pazzini       0
9                random5       0
8                 Eunuco       0
7              koke TFT        0
6                  Godi        0
5         Gabriel Passos       0
4                 Techzz       0
3              BES Toddy       0
32              random4        0

In [207]:
np_j1=np.arange(7,33,4)
np_j1=np.append(np_j1,0)
np_j1=np.sort(np_j1)

np_j2=np.arange(6,33,4)
np_j2=np.append(np_j2,1)
np_j2=np.sort(np_j2)


np_j3=np.arange(5,33,4)
np_j3=np.append(np_j3,2)
np_j3=np.sort(np_j3)

np_j4=np.arange(4,32,4)
np_j4=np.append(np_j4,3)
np_j4=np.sort(np_j4)





In [208]:
df_t

Nick  Pontos
1                DiPano        0
2                 Kazumi       0
31               random1       0
30                Sartii       0
29                  Xaue       0
28                 Maahs       0
27               Missao        0
26           Leo peixoto       0
25      Highroller Bnas        0
24                Kyoto        0
23                 Nyash       0
22               F 0 J O       0
21        Miguel Arkjow        0
20                 Dugra       0
19               Pedroca       0
18  Guilherme Maximiano        0
17           carluuuuuus       0
16                 Bieul       0
15          KDA Guiczar        0
14               random3       0
13                 Eddd        0
12               random2       0
11          xiellendario       0
10               Pazzini       0
9                random5       0
8                 Eunuco       0
7              koke TFT        0
6                  Godi        0
5         Gabriel Passos       0
4                 Techzz       0
3              BES Toddy       0
32              random4        0

In [209]:
np_j1,np_j2,np_j3,np_j4

(array([ 0,  7, 11, 15, 19, 23, 27, 31]),
 array([ 1,  6, 10, 14, 18, 22, 26, 30]),
 array([ 2,  5,  9, 13, 17, 21, 25, 29]),
 array([ 3,  4,  8, 12, 16, 20, 24, 28]))

In [210]:
list(np_j1)

[0, 7, 11, 15, 19, 23, 27, 31]

In [211]:
j1

Nick  Pontos  Jogo-1
0            Dugra      39     NaN
1  EUSOUHIPÓCRITA       33     NaN
2           b-nao       31     NaN
3          random1      27     NaN
4          random2      17     NaN
5            Eddd       11     NaN
6      Leo peixoto       7     NaN
7   Gabriel Passos       5     NaN

In [212]:
len(df_t)

32

In [213]:
j1=df_t.iloc[[0, 7, 11, 15, 19, 23, 27, 30]]

In [214]:
j1

Nick  Pontos
1                DiPano        0
26           Leo peixoto       0
22               F 0 J O       0
18  Guilherme Maximiano        0
14               random3       0
10               Pazzini       0
6                  Godi        0
3              BES Toddy       0

In [215]:
def shuffle(np_j1,np_j2,np_j3,np_j4,df1):
    j1=df1.iloc[list(np_j1)]
    j2=df1.iloc[list(np_j2)]
    j3=df1.iloc[list(np_j3)]
    j4=df1.iloc[list(np_j4)]
    
    return j1,j2,j3,j4

j1,j2,j3,j4=shuffle(np_j1,np_j2,np_j3,np_j4,df_t)

In [216]:
j1.index+=1
j2.index+=1
j3.index+=1
j4.index+=1

In [217]:
j1,j2,j3,j4

(                    Nick  Pontos
 2                DiPano        0
 27           Leo peixoto       0
 23               F 0 J O       0
 19  Guilherme Maximiano        0
 15               random3       0
 11               Pazzini       0
 7                  Godi        0
 33              random4        0,
             Nick  Pontos
 3         Kazumi       0
 28       Missao        0
 24         Nyash       0
 20       Pedroca       0
 16  KDA Guiczar        0
 12  xiellendario       0
 8      koke TFT        0
 4      BES Toddy       0,
        Nick  Pontos
 32  random1       0
 29    Maahs       0
 25   Kyoto        0
 21    Dugra       0
 17    Bieul       0
 13  random2       0
 9    Eunuco       0
 5    Techzz       0,
                 Nick  Pontos
 31            Sartii       0
 30              Xaue       0
 26  Highroller Bnas        0
 22    Miguel Arkjow        0
 18       carluuuuuus       0
 14             Eddd        0
 10           random5       0
 6     Gabriel Passos       

In [218]:
import requests

In [220]:
j1

Nick  Pontos
2                DiPano        0
27           Leo peixoto       0
23               F 0 J O       0
19  Guilherme Maximiano        0
15               random3       0
11               Pazzini       0
7                  Godi        0
33              random4        0

In [221]:
nick="F 0 J O"

In [222]:
puuid=requests.get(f"https://br1.api.riotgames.com/tft/summoner/v1/summoners/by-name/{nick}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
    
puuid=puuid["puuid"]
matchs=requests.get(f"https://americas.api.riotgames.com/tft/match/v1/matches/by-puuid/{puuid}/ids?count=4&api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()

partida=requests.get(f"https://americas.api.riotgames.com/tft/match/v1/matches/{matchs[0]}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
colocacoes=[]
for n in range(0,8):
    colocacoes.append(partida["info"]["participants"][n]["placement"])

participantes=partida["metadata"]["participants"]
nick_p=[]
for participante in participantes:
    nicks=requests.get(f"https://br1.api.riotgames.com/tft/summoner/v1/summoners/by-puuid/{participante}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
    nick_p.append(nicks["name"])  
# st.write(nick_p)

data_tuples = list(zip(nick_p,colocacoes))
pos=pd.DataFrame(data_tuples,columns=["Nick","Jogo-1"])
# st.dataframe(pos)
j1=j1.merge(pos,how="left",on="Nick")


In [224]:
data_tuples

[('EMS Leon', 5),
 ('tomate fresco', 2),
 ('F 0 J O', 3),
 ('Ethereal', 6),
 ('Faret', 8),
 ('EMS Morrïgan', 7),
 ('Yato Issei ', 4),
 ('lHinatal', 1)]

In [226]:
conv_dict=dict({1:10,2:8,3:7,4:6,5:4,6:3,7:2,8:1})

In [246]:
j1

Nick  Pontos  Jogo-1
0               DiPano        0     NaN
1           Leo peixoto       0     NaN
2               F 0 J O       0     3.0
3  Guilherme Maximiano        0     NaN
4               random3       0     NaN
5               Pazzini       0     NaN
6                 Godi        0     NaN
7              random4        0     NaN

In [247]:
j1.replace({"Jogo-1":conv_dict})

Nick  Pontos  Jogo-1
0               DiPano        0     NaN
1           Leo peixoto       0     NaN
2               F 0 J O       0     7.0
3  Guilherme Maximiano        0     NaN
4               random3       0     NaN
5               Pazzini       0     NaN
6                 Godi        0     NaN
7              random4        0     NaN

In [245]:
data_tuples[5][1]

7

In [242]:
for n,x in enumerate(data_tuples):
    print(n)

0
1
2
3
4
5
6
7


In [243]:
for n,x in enumerate(data_tuples):
    if data_tuples[n][1] == 1:
        data_tuples[n][1]=10
    elif data_tuples[n][1] == 2:
        data_tuples[n][1]=8
    elif data_tuples[n][1] == 3:
        data_tuples[n][1]=7
    elif data_tuples[n][1] == 4:
        data_tuples[n][1]=6
    elif data_tuples[n][1] == 5:
        data_tuples[n][1]=4
    elif data_tuples[n][1] == 6:
        data_tuples[n][1]=3
    elif data_tuples[n][1] == 7:
        data_tuples[n][1]=2
    else:
        data_tuples[n][1]=1
    
    
    
    

TypeError: 'tuple' object does not support item assignment