In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("jogadores.csv")

In [ ]:
df

In [ ]:
# df[["Jogo 1","Jogo 2", "Jogo 3", "Jogo 4", "Pontos"]]=0

In [ ]:
df1=df.sample(8)
df.drop(df1.index,inplace=True)
df2=df.sample(8)
df.drop(df2.index,inplace=True)
df3=df.sample(8)
df.drop(df3.index,inplace=True)
df4=df.sample(8)
df.drop(df4.index,inplace=True)
df5=df.sample(8)
df.drop(df5.index,inplace=True)
df6=df.sample(8)
df.drop(df6.index,inplace=True)
df7=df.sample(8)
df.drop(df7.index,inplace=True)

In [ ]:
df1.reset_index(drop=True,inplace=True)
df1.index+=1
df1

In [ ]:
df2.reset_index(drop=True,inplace=True)
df2.index+=1
df2

In [ ]:
df3.reset_index(drop=True,inplace=True)
df3.index+=1
df3

In [ ]:
df4.reset_index(drop=True,inplace=True)
df4.index+=1
df4

In [ ]:
df5.reset_index(drop=True,inplace=True)
df5.index+=1
df5

In [ ]:
df6.reset_index(drop=True,inplace=True)
df6.index+=1
df6

In [ ]:
df7.reset_index(drop=True,inplace=True)
df7.index+=1
df7

In [ ]:
df1[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df2[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df3[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df4[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df5[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df6[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0
df7[["Jogo 1","Jogo 2","Jogo 3","Jogo 4","Pontos"]]=0


In [ ]:
df1.to_csv("j1_Rodada-1.csv",index_label=False)
df2.to_csv("j2_Rodada-1.csv",index_label=False)
df3.to_csv("j3_Rodada-1.csv",index_label=False)
df4.to_csv("j4_Rodada-1.csv",index_label=False)
df5.to_csv("j5_Rodada-1.csv",index_label=False)
df6.to_csv("j6_Rodada-1.csv",index_label=False)
df7.to_csv("j7_Rodada-1.csv",index_label=False)

In [ ]:
df_styled = df.style.background_gradient()

In [ ]:
df1.export(df_styled,"mytable.png")


In [ ]:
df1=pd.read_csv("j1_Rodada-1.csv")
df2=pd.read_csv("j2_Rodada-1.csv")
df3=pd.read_csv("j3_Rodada-1.csv")
df4=pd.read_csv("j4_Rodada-1.csv")
df5=pd.read_csv("j5_Rodada-1.csv")
df6=pd.read_csv("j6_Rodada-1.csv")
df7=pd.read_csv("j7_Rodada-1.csv")

In [ ]:
df_t=pd.concat([df1,df2,df3,df4,df5,df6,df7])

In [ ]:
df_t.drop("Unnamed: 0",axis=1,inplace=True)

In [ ]:
df_t=df_t[["Nick","Pontos"]]

In [ ]:
df_t.reset_index(inplace=True,drop=True)

In [ ]:
df_t.index+=1

In [ ]:
# df_t.Pontos = np.random.randint(4,40, size=len(df_t))

In [ ]:
df_t=df_t.sort_values("Pontos",ascending=False)

In [ ]:
df_t["Pontos"]=0

In [1]:
df_t.to_csv("tabela.csv",index=False)

NameError: name 'df_t' is not defined

In [1]:
import pandas as pd
import numpy as np

In [2]:
rdd1=pd.read_csv("rdd6.csv",index_col=False)

In [3]:
rdd1

Nick  Pontos
0       BES Midor1ya     182
1          BES Toddy     173
2   BEE Xiellendario     166
3       BEE Phelpz13     164
4           TMT Xaue     163
5      Miguel Arkjow     163
6           BES Vipi     162
7         FOUR Bieul     156
8         vMetangTTV     156
9             zzhcet     155
10       KDA Guiczar     155
11   Highroller Bnas     154
12    BES Inc mplete     153
13      FOUR SaintOz     152
14        BEE Itachi     149
15        KDA Wenked     148
16         FOUR Jhin     147
17       Felipeanjos     143
18       PedroBanana     142
19         FOUR Koke     139
20       TFX D klein     138
21          BEE Soft     138
22          JosneyQT     133
23             Erith     133
24         vovô nuco     130
25   KDA ConsTanTine     128
26        EMS Sartii     128
27         D Pazzini     127
28        NDL Carlão     124
29   FOUR Steps Days     124
30         The Nextt     123
31             Faret     120
32              Godi     116
33          Kazzumii     116
34           F 0 J O     112
35       TMT Sneaky1     112
36  perfect comp tft     109
37     Dino Lothbrok     108
38     Senhor Mindua     103
39        TchxuunaiY     102

In [4]:
rdd1.index+=1

In [5]:
# rdd1.drop('Unnamed: 0',axis=1,inplace=True)

In [6]:
rdd1

Nick  Pontos
1       BES Midor1ya     182
2          BES Toddy     173
3   BEE Xiellendario     166
4       BEE Phelpz13     164
5           TMT Xaue     163
6      Miguel Arkjow     163
7           BES Vipi     162
8         FOUR Bieul     156
9         vMetangTTV     156
10            zzhcet     155
11       KDA Guiczar     155
12   Highroller Bnas     154
13    BES Inc mplete     153
14      FOUR SaintOz     152
15        BEE Itachi     149
16        KDA Wenked     148
17         FOUR Jhin     147
18       Felipeanjos     143
19       PedroBanana     142
20         FOUR Koke     139
21       TFX D klein     138
22          BEE Soft     138
23          JosneyQT     133
24             Erith     133
25         vovô nuco     130
26   KDA ConsTanTine     128
27        EMS Sartii     128
28         D Pazzini     127
29        NDL Carlão     124
30   FOUR Steps Days     124
31         The Nextt     123
32             Faret     120
33              Godi     116
34          Kazzumii     116
35           F 0 J O     112
36       TMT Sneaky1     112
37  perfect comp tft     109
38     Dino Lothbrok     108
39     Senhor Mindua     103
40        TchxuunaiY     102

In [7]:
np_j1=np.array([1,10,15,20,25,30,35,40])
np_j2=np.array([2,9,14,19,24,29,34,39])
np_j3=np.array([3,8,13,18,23,28,33,38])
np_j4=np.array([4,7,12,17,22,27,32,37])
np_j5=np.array([5,6,11,16,21,26,31,36])
# np_j6=np.array([6,7,13,19,25,31,37,43])


In [31]:
# np_j1=np.arange(12,49,8)
# np_j1=np.append(np_j1,1)
# np_j1=np.sort(np_j1)
# print(np_j1)

# np_j2=np.arange(11,49,8)
# np_j2=np.append(np_j2,2)
# np_j2=np.sort(np_j2)
# print(np_j2)


# np_j3=np.arange(10,49,8)
# np_j3=np.append(np_j3,3)
# np_j3=np.sort(np_j3)
# print(np_j3)

# np_j4=np.arange(9,49,8)
# np_j4=np.append(np_j4,4)
# np_j4=np.sort(np_j4)
# print(np_j4)

# np_j5=np.arange(8,49,8)
# np_j5=np.append(np_j5,5)
# np_j5=np.sort(np_j5)
# print(np_j5)

# np_j6=np.arange(7,49,8)
# np_j6=np.append(np_j6,6)
# np_j6=np.sort(np_j6)
# print(np_j6)


# # np_j7=np.arange(8,49,8)
# # np_j7=np.append(np_j7,7)
# # np_j7=np.sort(np_j7)
# # print(np_j7)

# # np_j8=np.arange(7,49,8)
# # np_j8=np.append(np_j8,8)
# # np_j8=np.sort(np_j8)
# # print(np_j8)


# # np_j2=np.append(np_j2,np_j8[-1])
# # np_j3=np.append(np_j3,np_j8[-2])
# # np_j4=np.append(np_j4,np_j8[-3])
# # np_j5=np.append(np_j5,np_j8[-4])
# # np_j6=np.append(np_j6,np_j8[-5])
# # np_j7=np.append(np_j7,np_j8[-6])


[ 1 12 20 28 36 44]
[ 2 11 19 27 35 43]
[ 3 10 18 26 34 42]
[ 4  9 17 25 33 41]
[ 5  8 16 24 32 40 48]
[ 6  7 15 23 31 39 47]


In [9]:
def shuffle(np_j1,np_j2,np_j3,np_j4,np_j5,df1):
    lista=[1,1,1,1,1,1,1,1]
    g1=df1.iloc[np_j1-lista]
    g2=df1.iloc[np_j2-lista]
    g3=df1.iloc[np_j3-lista]
    g4=df1.iloc[np_j4-lista]
    g5=df1.iloc[np_j5-lista]
    # g6=df1.iloc[np_j6-lista]
    # g7=df1.iloc[np_j7-lista]
    
    return g1,g2,g3,g4,g5

g1,g2,g3,g4,g5=shuffle(np_j1,np_j2,np_j3,np_j4,np_j5,rdd1)

In [ ]:
g1.to_csv(f"Rodada7_g1.csv")
g2.to_csv(f"Rodada7_g2.csv")
g3.to_csv(f"Rodada7_g3.csv")
g4.to_csv(f"Rodada7_g4.csv")
g5.to_csv(f"Rodada7_g5.csv")
# g6.to_csv(f"Rodada6_g6.csv")
# g7.to_csv(f"Rodada4_g7.csv")

In [11]:
g1.sort_values('Pontos' ,ascending=False,inplace=True)
g2.sort_values('Pontos' ,ascending=False,inplace=True)
g3.sort_values('Pontos' ,ascending=False,inplace=True)
g4.sort_values('Pontos' ,ascending=False,inplace=True)
g5.sort_values('Pontos' ,ascending=False,inplace=True)
# g6.sort_values('Pontos' ,ascending=False,inplace=True)
# g7.sort_values('Pontos' ,ascending=False,inplace=True)

In [ ]:
g6

In [ ]:
import requests

In [ ]:
j1

In [ ]:
nick="F 0 J O"

In [ ]:
puuid=requests.get(f"https://br1.api.riotgames.com/tft/summoner/v1/summoners/by-name/{nick}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
    
puuid=puuid["puuid"]
matchs=requests.get(f"https://americas.api.riotgames.com/tft/match/v1/matches/by-puuid/{puuid}/ids?count=4&api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()

partida=requests.get(f"https://americas.api.riotgames.com/tft/match/v1/matches/{matchs[0]}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
colocacoes=[]
for n in range(0,8):
    colocacoes.append(partida["info"]["participants"][n]["placement"])

participantes=partida["metadata"]["participants"]
nick_p=[]
for participante in participantes:
    nicks=requests.get(f"https://br1.api.riotgames.com/tft/summoner/v1/summoners/by-puuid/{participante}?api_key=RGAPI-138fd8e0-06f7-4c98-a83e-49402304c000").json()
    nick_p.append(nicks["name"])  
# st.write(nick_p)

data_tuples = list(zip(nick_p,colocacoes))
pos=pd.DataFrame(data_tuples,columns=["Nick","Jogo-1"])
# st.dataframe(pos)
j1=j1.merge(pos,how="left",on="Nick")


In [ ]:
data_tuples

In [ ]:
conv_dict=dict({1:10,2:8,3:7,4:6,5:4,6:3,7:2,8:1})

In [ ]:
j1

In [ ]:
j1.replace({"Jogo-1":conv_dict})

In [ ]:
data_tuples[5][1]

In [ ]:
for n,x in enumerate(data_tuples):
    print(n)

In [ ]:
for n,x in enumerate(data_tuples):
    if data_tuples[n][1] == 1:
        data_tuples[n][1]=10
    elif data_tuples[n][1] == 2:
        data_tuples[n][1]=8
    elif data_tuples[n][1] == 3:
        data_tuples[n][1]=7
    elif data_tuples[n][1] == 4:
        data_tuples[n][1]=6
    elif data_tuples[n][1] == 5:
        data_tuples[n][1]=4
    elif data_tuples[n][1] == 6:
        data_tuples[n][1]=3
    elif data_tuples[n][1] == 7:
        data_tuples[n][1]=2
    else:
        data_tuples[n][1]=1
    
    
    
    